---
eap_config_base: standalone-ha.xml
eap_offline_install: False
eap_enable_yml_config: True
eap_statistics_enabled: True
eap_apply_cp: True
eap_systemd_enable: True
eap_bind_addr_private: "{{ ansible_default_ipv4.address }}"
eap_bind_addr_management: 0.0.0.0
eap_instance_name: "{{ inventory_hostname }}"
eap_elytron_adapter: True
eap_yml_configs: [ eap_ymlconfig.yml.j2 ]
#eap_patch_version: 7.4.9

sso_admin_password: "redhat1!but12long"

addressbook_jdbc_url: "{{ site_jdbc_url }}/addressbook"

app_url: https://github.com/ansible-middleware/addressbook/releases/download/1.0.7/addressbook.war
